# Generated by Django 5.2.1 on 2025-06-20 09:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(choices=[('GF', 'GF'), ('1F', '1F'), ('2F', '2F'), ('3F', '3F'), ('4F', '4F'), ('5F', '5F'), ('6F', '6F'), ('7F', '7F'), ('RF', 'RF')], max_length=3)),
                ('flat_type', models.CharField(choices=[('Flat-A', 'Flat-A'), ('Flat-B', 'Flat-B'), ('Flat-C', 'Flat-C')], max_length=10)),
                ('unit', models.CharField(choices=[('Sft', 'Sft')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('name_of_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_bill.customer')),
                ('name_of_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_bill.project')),
            ],
        ),
    ]
