# Generated by Django 5.2.1 on 2025-06-20 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_address_customer_customer_address_and_more'),
        ('project', '0001_initial'),
        ('sales_bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesbill',
            name='name_of_customer',
        ),
        migrations.RemoveField(
            model_name='salesbill',
            name='name_of_project',
        ),
        migrations.AddField(
            model_name='salesbill',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='customer_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='location',
            field=models.CharField(choices=[('GF', 'GF'), ('1F', '1F'), ('2F', '2F'), ('3F', '3F'), ('4F', '4F'), ('5F', '5F'), ('6F', '6F'), ('7F', '7F'), ('RF', 'RF')], max_length=10),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='unit_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
