# Generated by Django 5.2.1 on 2025-07-04 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReceive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('material_type', models.CharField(blank=True, max_length=100)),
                ('material_group', models.CharField(blank=True, max_length=100)),
                ('receive_date', models.DateField(verbose_name='Receive Date')),
                ('channel_no', models.CharField(max_length=30, verbose_name='Channel No')),
                ('receive_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
