services:
  - type: web
    name: erp-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn erp.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: erp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: erp-db
    plan: free



