services:
  - type: web
    name: erp-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn erp.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: erp.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: erp-db
          property: connectionString
databases:
  - name: erp-db
    databaseName: erp
    user: erp_user

