# Generated by Django 5.2.1 on 2025-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_group',
            field=models.CharField(choices=[('Civil work Material', 'Civil work Material'), ('Sanitary work Material', 'Sanitary work Material'), ('Electrical work Material', 'Electrical work Material'), ('NA', 'NA')], max_length=30, verbose_name='Group of Resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_unit',
            field=models.CharField(choices=[('Pcs', 'Pcs'), ('Nos', 'Nos'), ('Kg', 'Kg'), ('Lit', 'Lit')], max_length=10, verbose_name='Resource Unit'),
        ),
    ]
