# Generated by Django 5.2.1 on 2025-07-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_alter_resource_resource_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name_of_resource',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_group',
            field=models.CharField(choices=[('Civil work Material', 'Civil work Material'), ('Sanitary work Material', 'Sanitary work Material'), ('Electrical work Material', 'Electrical work Material')], max_length=30, verbose_name='Group of Resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_unit',
            field=models.CharField(max_length=50),
        ),
    ]
