"""
Django settings for erp project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os  # ← This must come before BASE_DIR


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = 'django-insecure-5zm*hq5#@p43-6uq)png8kszf)ppe8wuujk@(yd-eodnauzvi('

DEBUG = False

ALLOWED_HOSTS = ['DSC-django-App.azurewebsites.net']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'construction_department',
    'project',
    'resource',
    'customer',
    'material',
    'material_receive',
    'supplier',
    'sales_bill',
    'resource_receive',  # Your custom app
    'design_department',
    'inventory_department',
    'task',
    'employee',
    'work_plan',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'erp.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'material_receive_db',  # Database for Material Receive
        'USER': 'postgres',
        'PASSWORD': 'DEFGdefg2345',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'customer_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'customer_db',  # Database for Customer
        'USER': 'postgres',
        'PASSWORD': 'DEFGdefg2345',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'material_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'material_db',  # Database for Material
        'USER': 'postgres',
        'PASSWORD': 'DEFGdefg2345',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'task_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'task_db',  # Database for Task
        'USER': 'postgres',
        'PASSWORD': 'DEFGdefg2345',
        'HOST': 'localhost',
        'PORT': '5432',
    },
}


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'erp.settings')



# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

