# Generated by Django 5.2.1 on 2025-07-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(max_length=100, verbose_name='Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_resource', models.CharField(max_length=100, verbose_name='Resource Name')),
                ('resource_unit', models.CharField(max_length=10, verbose_name='Resource Unit')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceReceive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=10, verbose_name='Unit')),
                ('receive_date', models.DateField(verbose_name='Receive Date')),
                ('channel_no', models.CharField(max_length=30, verbose_name='Channel No')),
                ('receive_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Received Quantity')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_receive.project', verbose_name='Project')),
                ('resource_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_receive.resource', verbose_name='Resource')),
            ],
        ),
    ]
