# Generated by Django 5.2.1 on 2025-07-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('resource', '0002_alter_resource_resource_group_and_more'),
        ('resource_receive', '0002_alter_resourcereceive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcereceive',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='resourcereceive',
            name='resource_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resource.resource'),
        ),
        migrations.AlterField(
            model_name='resourcereceive',
            name='receive_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resourcereceive',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
