# Generated by Django 5.2.1 on 2025-07-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_material', models.CharField(max_length=255)),
                ('material_unit', models.CharField(max_length=100)),
                ('type_of_material', models.CharField(max_length=100)),
                ('group_of_material', models.CharField(max_length=100)),
            ],
        ),
    ]
