# Generated by Django 5.2.1 on 2025-06-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructiondepartment',
            options={'permissions': [('can_access_construction_department', 'Can access Construction Department')]},
        ),
        migrations.RenameField(
            model_name='constructiondepartment',
            old_name='name',
            new_name='title',
        ),
    ]
