# Generated by Django 5.2.1 on 2025-06-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_department', '0002_alter_constructiondepartment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConstructionDepartment',
        ),
    ]
