# Generated by Django 5.2.1 on 2025-06-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_project', models.CharField(max_length=255)),
                ('type_of_project', models.CharField(choices=[('DEA', 'DEA'), ('New Project', 'New Project')], max_length=50)),
                ('name_of_work', models.CharField(max_length=255)),
                ('work_unit', models.CharField(choices=[('Sft', 'Square Feet'), ('Cft', 'Cubic Feet'), ('Nos', 'Numbers'), ('Pcs', 'Pieces')], max_length=50)),
                ('name_of_contractors_company', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
