# Generated by Django 5.2.1 on 2025-06-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_supplier', models.CharField(max_length=255)),
                ('supplier_address', models.CharField(max_length=500)),
                ('supplier_contact_no', models.CharField(max_length=20)),
            ],
        ),
    ]
